language: go
go:
  - 1.13.x
env:
  global:
    - secure: L3qspsLzIjGxx4R6zJ/XDC7HqsY0HLHf0RdfNGSeEfQheMKkPPlT9i/163QIT3N0YA3wMHVUPb8wCq3HXR5sncjNu6LABt/g5CtfFnaWwZ0fom1/7OdC1KMekvlwqDsnUqVyjZQozSfrAmPTmO26F7059175awb2pxneNYEh0hA9rDN/1WhlZ/ma6kQ2k6VyHECZfc1ELAWjfZpfcdOcK5s6mXKM2lyI6NzZFLc2kkFJ9Hk2TfpyWOST1KZUhB6uhKy768CSoLCs5YuIpO2Uq4rpbUF0gNARbC/HcbDpWou/P4upXsQ5GG/jeOHkUzBtGrCd2IhUBcvNb0gor99sEBFKYRwdbelqN3XUr7xwtHFtBXyKr3tCpYcDpvtasqUG1/0+cBiSfRv2pIaHxh7KczubtYwsdIv2x7M89sD/7nvgjbgkGfLwLxBfMFleBtp3fIIQpKoq2bSM7YMJU+IzerErAGevpjE09VwzX1pzdrmNZEX3w5Xgmq7z+MI8K5/MHW1aRXcgT3bRszKH/QgeC+u096vSUvVS+tY6+9TwuARsCtGvHNttKm5yw5VST2jX8QbmNp6AHLdOzoC2/mp+97THz+Avrxm6bYH9y0a01VDz21g7INePGlAoz+6Yk2cNpE74fZymdwseexefPbCh0vlgd2gU2DqYfX33eXmtL+Y=
    - secure: nJDSL/MRdQWBEWPBVA/mh/ZP0lrL9bsb8PD5K4Es6J6Ftg6Swl/sWLD7BPp/95/HqHodizVDQqDa+qrBaGany+Srr1S1QYb7RNIwMwh7kUsU8IMTzQjEHlP1027YNW+yjoMJI0u38n+E0pKetqEdha90lNegTrhhxhCYSs0jrUyNcFpxi5SnE3IgnFOP0GGPa07h+2h9MoJV3I417PrrGQk6JG5iYL9LYnNZglwykXck1wMlQKE8GBJvaSu8js2cIRcGK77JY3Tzoumfaw0Fp8TVMl344niqjIhm8veATenenlHSljViN/iGbFXhU1cj4p53Afq5kLa3Lzdy0ChfRBB9NwZRErLPtpXCG4mnkyoF/O8BXFXeVxul2B8ligZ5iojHQ9JqgbAkV3p9Xpz/PZOk4VMbYeJPtDCZ3Fei+4HSrVLWVhuiOVfNDf46gBEXaW7OFxSQky8ZHQNLgiZVodKXyWOqObBeWKdTM05Tf6ZRmNxi/XzYCvbfGSjnx7vcX1Qy/1CtOnXYN8b4MRcmyAl4pgGvC/clJWMY3lsJ6Vwe6af0MoSK2laJTcqi+A3qbrFdYik7SwxtGcBwY2DQuOcWqVhAdGVDZd5Gpw2eUH/dFb5NUllhnC5fnk0KgjK7SWrrKZHEZ6wn6KmwQZE6+e4O9I/+4Kd0AD1BRpItKbE=
jobs:
  include:
    - stage: lint
      install:
        - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.6
      script:
        - ls
        - ls compose
        - make lint
    - stage: test
      script: make testacc
      if: branch = master
    - stage: build
      script: make build
    - stage: deploy
      install:
        - go get github.com/mitchellh/gox
      script: skip
      before_deploy:
        - mkdir releases
        - gox -os="darwin" -arch="amd64" -output="releases/{{.Dir}}_${TRAVIS_TAG}_{{.OS}}_{{.Arch}}"
      deploy:
        draft: true
        provider: releases
        api_key: $GITHUB_TOKEN
        skip_cleanup: true
        file_glob: true
        file: releases/*
        on:
          tags: true
