---
language: go

go:
  - 1.13.x

jobs:
  include:
    - stage: install requirements
      script:
        - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.6
    - stage: lint
      script: make lint
    - stage: test
      script: make test
    - script: make testacc
      if: branch = master
    - stage: build
      script: make build
    - stage: deploy
      script: skip
      before_deploy:
        - mkdir releases
        - gox -os="darwin" -arch="amd64" -output="releases/{{.Dir}}_${TRAVIS_TAG}_{{.OS}}_{{.Arch}}"
      deploy:
        draft: true
        provider: releases
        api_key:
          secure: VZdJqRIHXMJIiLXRu3ZouPh2wYgI2REtneZ8g+A2IVmI96+I5/XWp2AtWJWDOBFDUje1xEdNpVDfwhmmFRgXcbYaGfhksFPNbYi1APetgggZ8r2DR6pV13APT071rt8zuG2IkNFvHHBU52yoFET9I9Jx1iWI3flMXBQJKrqSK0og/ovv4nK30wfBG+0hYCQXBANsQHUG4NM/h3HwMa4sPmzYEML+P/LH9yF8nRbri9mbrO+onm/0sAPh3wcElfYtzgHCk21PbOyHUdbIVMlL/ck6TlNAJualI0R8veg3/hlP2rEJP7d9baXQmLAJKeZp2HPl8G86e5ITZfmffFbpHLvK85hdPi1CL3uXq08R22RtJsLMPsZbEOAFCgwJEeccEwclNuzRch5kJi6rTJjJ8n2wdERChOHuNQmNeo4zvoxkYgIXtwSIH4LASiR2njViC2ZfKnRxl3iYBULBuEbP29jeHrkurX5uCBD4nlhr8merslnLfoBfmxklQxsypwSrGxcWCnxgVpHOcfU2f+jwKE3vLxUYNlteQPkW/R6u/MXbjS/s1oEybwhbVeQLcB4HFTbmMrh06CuzG9FmSiS7jwFB4sBix/k8MYzY431JRr7JBG1oKblOC9xpilVM6Nzk0m5FJ9yQYxGZqO9gsrPRe3NqnJJQNtg2rqiFhOj/jlI=
        skip_cleanup: true
        file_glob: true
        file: releases/*
        on:
          tags: true
