language: go
go:
  - 1.13.x
jobs:
  include:
    - stage: lint
      install:
        - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.6
      script: make lint
    - stage: build
      script: make build
    - stage: test
      script: make test
    - script: make testacc
      if: branch = master
    - stage: deploy
      install:
        - go get github.com/mitchellh/gox
      script: skip
      before_deploy:
        - mkdir releases
        - gox -os="darwin linux windows" -arch="amd64" -output="releases/{{.Dir}}_${TRAVIS_TAG}_{{.OS}}_{{.Arch}}"
      deploy:
        draft: true
        provider: releases
        api_key: $GITHUB_TOKEN
        skip_cleanup: true
        file_glob: true
        file: releases/*
        on:
          tags: true
